server:
  log_level: debug

traces:
  configs:
  - name: server_traces
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"
          grpc:
            endpoint: "0.0.0.0:4319"

    remote_write:
      - endpoint: tempo:4317
        insecure: true

    automatic_logging:
      backend: stdout
      roots: true

    # service_graphs:
    #   enabled: true

# metrics:
#   configs:
#     - name: default
#       scrape_configs:
#         - job_name: local_scrape
#           static_configs:
#             - targets: ['127.0.0.1:12345']
#       remote_write:
#         - url: <remote_write>